config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'home#index'

    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    post 'auth/:provider', to: 'auth#request', as: :auth_request

    delete 'auth/logout'

    resources :repositories, only: %i[index show new create update] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
    end
  end

  namespace :api do
    resources :checks, only: %i[create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  extend Enumerize

  belongs_to :user
  has_many :checks, dependent: :destroy

  enumerize :language, in: %i[javascript ruby]

  validates :github_id, uniqueness: true, presence: true

  def path_to_directory
    File.join(Dir.tmpdir, 'viledev_quality_repositories/', full_name)
  end
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM

  belongs_to :repository

  aasm do
    state :created, initial: true
    state :checking, :finished, :failed

    event :run_check do
      transitions from: :created, to: :checking
    end

    event :finish do
      transitions from: :checking, to: :finished
    end

    event :fail do
      transitions from: :checking, to: :failed
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :repositories, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

module Api
  class ApplicationController < ApplicationController
    skip_before_action :verify_authenticity_token
  end
end

app/controllers/api/checks_controller.rb
# frozen_string_literal: true

module Api
  class ChecksController < Api::ApplicationController
    def create
      full_name = params[:repository][:full_name]
      repository = Repository.find_by(full_name:)

      unless repository
        head :not_found
        return
      end

      check = repository.checks.create!

      CheckRepositoryJob.perform_later(check.id)

      head :ok
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/concerns/auth_management.rb
# frozen_string_literal: true

module AuthManagement
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def check_admin
    return if current_user&.admin?

    redirect_to root_path, notice: t('.notice')
  end

  def signed_in?
    session[:user_id].present? && current_user.present?
  end

  private

  def authenticate_user!
    return if signed_in?

    flash[:alert] = t('.should_sign_in')
    redirect_to root_path
  end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

module Web
  class ApplicationController < ApplicationController
    include Pundit::Authorization
    include AuthManagement

    before_action :authenticate_user!

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
      flash[:alert] = t('flash.not_authorized')

      redirect_to root_path
    end
  end
end

app/controllers/web/auth_controller.rb
# frozen_string_literal: true

module Web
  class AuthController < Web::ApplicationController
    skip_before_action :authenticate_user!

    def callback
      data = request.env['omniauth.auth']
      user = get_user_by(data)

      if user.save
        session['user_id'] = user.id
        flash[:notice] = t('.success')
      else
        flash[:alert] = t('.fail')
      end

      redirect_to root_path
    end

    def logout
      session.delete('user_id')
      flash[:notice] = t('.success')

      redirect_to root_path
    end

    private

    def get_user_by(data)
      email = data.dig('info', 'email')

      user = User.find_or_initialize_by(email:)

      user.token = data.dig('credentials', 'token')
      user.nickname = data.dig('info', 'nickname')
      user.provider = data['provider']
      user.uid = data['uid']

      user
    end
  end
end

app/controllers/web/home_controller.rb
# frozen_string_literal: true

module Web
  class HomeController < Web::ApplicationController
    skip_before_action :authenticate_user!, only: [:index]

    def index; end
  end
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ApplicationController < Web::ApplicationController
    end
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ChecksController < Web::Repositories::ApplicationController
      def show
        @check = ::Repository::Check.includes(:repository).find(params[:id])

        authorize @check

        if !@check.finished? && !@check.failed?
          flash[:notice] = t('.check_in_progress')
          redirect_to @check.repository and return
        end

        parsed_check_details = JSON.parse(@check.details.presence || '{}')
        @check_result = LogFormatter.format(parsed_check_details, @check.repository.language)
      end

      def create
        @repository = ::Repository.find(params[:repository_id])
        check = @repository.checks.create!

        authorize check

        CheckRepositoryJob.perform_later(check.id)

        flash[:notice] = t('.success')
        redirect_to @repository
      end
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

module Web
  class RepositoriesController < Web::ApplicationController
    def index
      @repositories = current_user.repositories.includes(:checks).page(params[:page])
    end

    def show
      @repository = ::Repository.find(params[:id])

      authorize @repository

      @checks = @repository.checks.order(id: :desc).page(params[:page])
    end

    def new
      @repository = current_user.repositories.build
      @github_client = AppContainer[:github_client].new(repository: @repository, user: current_user)

      authorize @repository

      @repositories = fetch_github_repositories
    end

    def create
      @repository = current_user.repositories.find_or_initialize_by(repository_params)

      authorize @repository

      if @repository.save
        UpdateInfoRepositoryJob.perform_later(@repository.id)
        redirect_to repositories_path, notice: t('.success')
      else
        flash[:alert] = @repository.errors.full_messages.join('\n')
        redirect_to action: :new
      end
    end

    private

    def repository_params
      params.require(:repository).permit(:github_id)
    end

    def fetch_github_repositories
      cache_key = "#{current_user.cache_key_with_version}/github_repositories"
      Rails.cache.fetch(cache_key, expires_in: 12.hours) do
        @github_client.repos_collection
      end
    end
  end
end

app/helpers/api/check_helper.rb
# frozen_string_literal: true

module Api
  module CheckHelper
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def link_to_github(check, options = {})
    commit_id = check.commit_id

    return '' if check.commit_id.blank?

    file_path = options.delete(:file_path)

    commit_path =
      if file_path.present?
        file_relative_path = file_path.remove(check.repository.path_to_directory).delete_prefix('/')

        "/tree/#{commit_id}/#{file_relative_path}"
      else
        "/commit/#{commit_id}"
      end

    repository_full_name = check.repository.full_name

    link_to file_relative_path, "https://github.com/#{repository_full_name}#{commit_path}", options
  end
end

app/helpers/web/home_helper.rb
# frozen_string_literal: true

module Web
  module HomeHelper
  end
end

app/helpers/web/repository/checks_helper.rb
# frozen_string_literal: true

module Web
  module Repository
    module ChecksHelper
    end
  end
end

app/helpers/web/repository/repositories_helper.rb
# frozen_string_literal: true

module Web
  module Repository
    module RepositoriesHelper
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t('.title')
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application',
            'data-turbo-track': 'reload', type: 'module'
  body.d-flex.flex-column.h-100
    = render 'layouts/shared/nav'
    = render 'layouts/shared/flash'
    main = yield

app/views/layouts/shared/_flash.html.slim
- if flash[:notice]
  .container.my-2
    .alert.alert-info = flash[:notice]
-if flash[:alert]
  .container.my-2
    .alert.alert-danger = flash[:alert]

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand.me-md-4'
        = image_tag 'logo.png', width: '30'

      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2
            = link_to t('.home'), root_path, class: 'nav-link text-dark'
          - if signed_in?
            li.nav-item.me-2
              = link_to t('.repositories'), repositories_path, class: 'text-dark nav-link'
    ul.nav.nav-pills
      - if signed_in?
        li.nav-item
          = link_to current_user.email, '#', class: 'nav-link text-secondary'
        li.nav-item
          = button_to t('.logout'), auth_logout_path,
                  data: { turbo: false },
                  class: 'nav-link text-dark'
      - else
        li.nav-item.me-2
          = button_to t('.sign_in_with_github'), auth_request_path('github'),
                  data: { turbo: false },
                  class: 'nav-link text-dark'

app/views/web/home/index.html.slim
.mt-4.mb-5.pb-5
  .container
    .p-4.align-items-center.border.shadow.bg-white.rounded-3
      .mb-4
      .display-4.fw-bold.mb-0 = t('.greetings')
      p.mb-4 = t('.courses_description')
      h2.fw-bold = t('.title')
      p = t('.project_description_html')
      = link_to t('.more'),
              'https://ru.hexlet.io/programs/rails/projects/66',
              class: 'btn btn-primary btn-lg px-4 mt-3 fw-bold'

app/views/web/repositories/checks/show.html.slim
.mt-4.mb-5.pb-5
  .container
    .p-4.align-items-center.border.shadow.bg-white.rounded-3
      .mb-4
      = link_to t('.to_repository'), @check.repository,
              class: 'btn btn-primary mb-4'
      h1 = t('.title', check_id: @check.id)
      table.table
        tbody
          tr
            td = t('.created_at')
            td = l(@check.created_at, format: :full)
          tr
            td = t('.status')
            td = @check.aasm.human_state
          tr
            td = t('.check_passed')
            td = @check.passed?
          tr
            td = t('.issues_count')
            td = @check_result[:offense_count]
          tr
            td = t('.commit_id')
            td
              - if @check.commit_id
                = link_to_github(@check, target: '_blank')
      table.table.table-hover.mb-5
        thead
          tr
            th = t('.message')
            th = t('.rule_id')
            th = t('.line_column')
            tbody
              - @check_result[:files].each do |file_record|
                tr
                  td colspan=3
                    = link_to_github(@check, file_path: file_record[:path])
                - file_record[:offenses].each do |offense|
                  tr
                    td = offense[:message]
                    td = offense[:rule]
                    td = offense[:location]

app/views/web/repositories/index.html.slim
.mt-4.mb-5.pb-5
  .container
    .p-4.align-items-center.border.shadow.bg-white.rounded-3
      .mb-4
      = link_to t('.new'), new_repository_path, class: 'btn btn-primary'
      table.table.table-striped.table-hover.mt-4
        thead
          tr
            th scope="col" = t('.name')
            th scope="col" = t('.language')
            th scope="col" = t('.last_check_passed')
        tbody
          - @repositories.each do |repository|
            tr
              td = link_to repository.name || '-', repository_path(repository)
              td = repository.language
              td
                = repository.checks.last ? repository.checks.last.passed? : t('.no_checks_yet')

= paginate @repositories, theme: 'bootstrap-5'

app/views/web/repositories/new.html.slim
.mt-4.mb-5.pb-5
  .container
    .p-4.align-items-center.border.shadow.bg-white.rounded-3
      .mb-4
        = render 'web/repositories/shared/form', repository: @repository

app/views/web/repositories/shared/_form.html.slim
= simple_form_for :repository, url: repositories_path, method: :post do |f|
  = f.input :github_id, as: :select, collection: @repositories
  = f.button :submit, class: 'btn btn btn-success'

app/views/web/repositories/show.html.slim
.mt-4.mb-5.pb-5
  .container
    .p-4.align-items-center.border.shadow.bg-white.rounded-3
      .mb-4
        h1 = @repository.full_name
      = button_to t('.check'), repository_checks_path(@repository),
              class: 'btn btn-primary mb-4'
      p
        strong.me-2 = t('.name')
        = @repository.full_name
      p
        strong.me-2 = t('.language')
        = @repository.language
      p
        strong.me-2 = t('.created_at')
        = l(@repository.created_at, format: :full)
      p
        strong.me-2 = t('.updated_at')
        = l(@repository.updated_at, format: :full)
      hr

      - if @checks.any?
        table.table.table-striped
          thead
            tr
              th scope='col'
              th scope='col' = t('.status')
              th scope='col' = t('.commit_id')
              th scope='col' = t('.check_passed')
              th scope='col' = t('.created_at')
          tbody
            - @checks.each do |check|
              tr
                td = link_to((check.id + 1), repository_check_path(@repository, check))
                td = check.aasm.human_state
                td
                  - if check.commit_id
                    = link_to_github(check, target: '_blank')
                td = check.passed?
                td = l(check.created_at, format: :short)
        = paginate @checks